# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shinsaeki <shinsaeki@student.42.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/19 23:02:19 by shinsaeki         #+#    #+#              #
#    Updated: 2023/11/19 23:04:37 by shinsaeki        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	g++ -o UnnecessaryViolence main.cpp HumanA.cpp Weapon.cpp
clean:
	rm -f UnnecessaryViolence
fclean: clean
re: fclean all