# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shinsaeki <shinsaeki@student.42.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/20 12:10:35 by shinsaeki         #+#    #+#              #
#    Updated: 2023/11/20 12:11:24 by shinsaeki        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	g++ -o Fixed main.cpp Fixed.cpp
clean:
	rm -f UnnecessaryViolence
fclean: clean
re: fclean all