# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shinsaeki <shinsaeki@student.42.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/13 13:58:42 by shinsaeki         #+#    #+#              #
#    Updated: 2023/11/13 14:25:27 by shinsaeki        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	g++ -o Zombie main.cpp Zombie.cpp newZombie.cpp randomChump.cpp
clean:
	rm -f Zombie
re: clean all